version: '3'

services:

  # app-nestjs:
  #   build: ./app
  #   ports:
  #     - ${BACKEND_API_PORT}:3000
  #   depends_on:
  #     - db
  #     - keycloak

  postgres:
    image: postgres
    ports:
      - ${DB_MAIN_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_MAIN_USER}
      POSTGRES_PASSWORD: ${DB_MAIN_PASSWORD}
      POSTGRES_DB: ${DB_MAIN_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data


volumes:
  postgres_data:
  keycloak_data:
