version: '3'

services:

  # app-nestjs:
  #   build: ./app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #     - keycloak

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_MAIN_USER}
      POSTGRES_PASSWORD: ${DB_MAIN_PASSWORD}
      POSTGRES_DB: ${DB_MAIN_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 9080:8080
    # volumes:
    #   - keycloak_data:/opt/jboss/keycloak/standalone/data

  
volumes:
  postgres_data:
  # keycloak_data:
